POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "robert1",
    "password": "password123"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "root",
    "password": "root"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "kha",
    "password": "asdfasdf"
}

###
GET http://localhost:3003/api/users/61b0151ad0c21dd581e4e578